routes/admin.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
This route respond for api/admin*
|
*/

    
Route::middleware('guest')->get('/'             , ['as'=>'admin.index'                              , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@index']);
Route::middleware('guest')->post('/login_json'  , ['as'=>'admin.login.login_json'                   , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@login_json']);
Route::middleware('guest')->post('/login'       , ['as'=>'admin.login.login'                        , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@login']);
Route::middleware('guest')->get('/logout'       , ['as'=>'admin.login.logout'                      , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@logout']);
Route::middleware('guest')->get('/form_login'   , ['as'=>'admin.login.form_login'                   , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@index']);
Route::group(['middleware' => 'auth:admin'], function () {
    Route::get('/admin_users/edit/{admin_users}'                        , ['as'=>'admin.admin_users.edit'           , 'uses'=>'App\Http\Controllers\Admin\AdminUsersController@edit']);
    Route::get('/admin_users/create'                                    , ['as'=>'admin.admin_users.create'         , 'uses'=>'App\Http\Controllers\Admin\AdminUsersController@create']);
    Route::apiResource('admin_users'                                    , 'App\Http\Controllers\Admin\AdminUsersController'                 , ['as' => 'admin', 'parameters' => [ 'admin_users'              => 'admin_users']]);
    
    Route::get('/control_points/edit/{control_points}'                  , ['as'=>'admin.control_points.edit'           , 'uses'=>'App\Http\Controllers\Admin\ControlPointsController@edit']);
    Route::get('/control_points/create'                                 , ['as'=>'admin.control_points.create'         , 'uses'=>'App\Http\Controllers\Admin\ControlPointsController@create']);
    Route::apiResource('control_points'                                 , 'App\Http\Controllers\Admin\ControlPointsController'              , ['as' => 'admin', 'parameters' => [ 'control_points'           => 'control_points']]);
    
    Route::get('/cost_centers/edit/{cost_centers}'                      , ['as'=>'admin.cost_centers.edit'           , 'uses'=>'App\Http\Controllers\Admin\CostCentersController@edit']);
    Route::get('/cost_centers/create'                                   , ['as'=>'admin.cost_centers.create'         , 'uses'=>'App\Http\Controllers\Admin\CostCentersController@create']);
    Route::apiResource('cost_centers'                                   , 'App\Http\Controllers\Admin\CostCentersController'                , ['as' => 'admin', 'parameters' => [ 'cost_centers'             => 'cost_centers']]);
    
    Route::get('/departaments/edit/{departaments}'                      , ['as'=>'admin.departaments.edit'           , 'uses'=>'App\Http\Controllers\Admin\DepartamentsController@edit']);
    Route::get('/departaments/create'                                   , ['as'=>'admin.departaments.create'         , 'uses'=>'App\Http\Controllers\Admin\DepartamentsController@create']);
    Route::apiResource('departaments'                                   , 'App\Http\Controllers\Admin\DepartamentsController'                , ['as' => 'admin', 'parameters' => [ 'departaments'             => 'departaments']]);

    Route::get('/events/edit/{events}'                                  , ['as'=>'admin.events.edit'           , 'uses'=>'App\Http\Controllers\Admin\EventsController@edit']);
    Route::get('/events/create'                                         , ['as'=>'admin.events.create'         , 'uses'=>'App\Http\Controllers\Admin\EventsController@create']);
    Route::apiResource('events'                                         , 'App\Http\Controllers\Admin\EventsController'                     , ['as' => 'admin', 'parameters' => [ 'events'                   => 'events']]);
    
    Route::get('/event_expense_natures/edit/{event_expense_natures}'    , ['as'=>'admin.event_expense_natures.edit'           , 'uses'=>'App\Http\Controllers\Admin\EventExpenseNaturesController@edit']);
    Route::get('/event_expense_natures/create'                          , ['as'=>'admin.event_expense_natures.create'         , 'uses'=>'App\Http\Controllers\Admin\EventExpenseNaturesController@create']);
    Route::apiResource('event_expense_natures'                          , 'App\Http\Controllers\Admin\EventExpenseNaturesController'        , ['as' => 'admin', 'parameters' => [ 'event_expense_natures'    => 'event_expense_natures']]);
    
    Route::get('/event_receipts/edit/{event_receipts}'                  , ['as'=>'admin.event_receipts.edit'           , 'uses'=>'App\Http\Controllers\Admin\EventReceiptsController@edit']);
    Route::get('/event_receipts/create'                                 , ['as'=>'admin.event_receipts.create'         , 'uses'=>'App\Http\Controllers\Admin\EventReceiptsController@create']);
    Route::apiResource('event_receipts'                                 , 'App\Http\Controllers\Admin\EventReceiptsController'              , ['as' => 'admin', 'parameters' => [ 'event_receipts'           => 'event_receipts']]);
    
    Route::get('/expenses/edit/{expenses}'                              , ['as'=>'admin.expenses.edit'           , 'uses'=>'App\Http\Controllers\Admin\ExpensesController@edit']);
    Route::get('/expenses/create'                                       , ['as'=>'admin.expenses.create'         , 'uses'=>'App\Http\Controllers\Admin\ExpensesController@create']);
    Route::apiResource('expenses'                                       , 'App\Http\Controllers\Admin\ExpensesController'                   , ['as' => 'admin', 'parameters' => [ 'expenses'                 => 'expenses']]);
    
    Route::get('/expense_natures/edit/{expense_natures}'                , ['as'=>'admin.expense_natures.edit'           , 'uses'=>'App\Http\Controllers\Admin\ExpenseNaturesController@edit']);
    Route::get('/expense_natures/create'                                , ['as'=>'admin.expense_natures.create'         , 'uses'=>'App\Http\Controllers\Admin\ExpenseNaturesController@create']);
    Route::apiResource('expense_natures'                                , 'App\Http\Controllers\Admin\ExpenseNaturesController'             , ['as' => 'admin', 'parameters' => [ 'expense_natures'          => 'expense_natures']]);
    
    Route::get('/expense_receipts/edit/{expense_receipts}'              , ['as'=>'admin.expense_receipts.edit'           , 'uses'=>'App\Http\Controllers\Admin\ExpenseReceiptsController@edit']);
    Route::get('/expense_receipts/create'                               , ['as'=>'admin.expense_receipts.create'         , 'uses'=>'App\Http\Controllers\Admin\ExpenseReceiptsController@create']);
    Route::apiResource('expense_receipts'                               , 'App\Http\Controllers\Admin\ExpenseReceiptsController'            , ['as' => 'admin', 'parameters' => [ 'expense_receipts'         => 'expense_receipts']]);
    
    Route::get('/payment_forms/edit/{payment_forms}'                    , ['as'=>'admin.payment_forms.edit'           , 'uses'=>'App\Http\Controllers\Admin\PaymentFormsController@edit']);
    Route::get('/payment_forms/create'                                  , ['as'=>'admin.payment_forms.create'         , 'uses'=>'App\Http\Controllers\Admin\PaymentFormsController@create']);
    Route::post('/payment_forms/index_manager'                          , ['as'=>'admin.payment_forms.index_manager'  , 'uses'=>'App\Http\Controllers\Admin\PaymentFormsController@index_manager']);
    Route::apiResource('payment_forms'                                  , 'App\Http\Controllers\Admin\PaymentFormsController'               , ['as' => 'admin', 'parameters' => [ 'payment_forms'            => 'payment_forms']]);
    
    Route::get('/subsidiaries/edit/{subsidiaries}'                      , ['as'=>'admin.subsidiaries.edit'           , 'uses'=>'App\Http\Controllers\Admin\SubsidiariesController@edit']);
    Route::get('/subsidiaries/create'                                   , ['as'=>'admin.subsidiaries.create'         , 'uses'=>'App\Http\Controllers\Admin\SubsidiariesController@create']);
    Route::apiResource('subsidiaries'                                   , 'App\Http\Controllers\Admin\SubsidiariesController'               , ['as' => 'admin', 'parameters' => [ 'subsidiaries'             => 'subsidiaries']]);
    
    Route::get('/unit_measurements/edit/{unit_measurements}'            , ['as'=>'admin.unit_measurements.edit'           , 'uses'=>'App\Http\Controllers\Admin\UnitMeasurementsController@edit']);
    Route::get('/unit_measurements/create'                              , ['as'=>'admin.unit_measurements.create'         , 'uses'=>'App\Http\Controllers\Admin\UnitMeasurementsController@create']);
    Route::apiResource('unit_measurements'                              , 'App\Http\Controllers\Admin\UnitMeasurementsController'           , ['as' => 'admin', 'parameters' => [ 'unit_measurements'        => 'unit_measurements']]);
    
    Route::get('/users/edit/{users}'                            , ['as'=>'admin.users.edit'           , 'uses'=>'App\Http\Controllers\Admin\UsersController@edit']);
    Route::get('/users/create'                                  , ['as'=>'admin.users.create'         , 'uses'=>'App\Http\Controllers\Admin\UsersController@create']);
    Route::apiResource('users'                                  , 'App\Http\Controllers\Admin\UsersController'                      , ['as' => 'admin', 'parameters' => [ 'users'                    => 'users']]);

routes/front.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/
Route::middleware('guest')->post('/login_json', ['as'=>'front.login.login_json'                  , 'uses'=>'App\Http\Controllers\Auth\LoginUsersController@login_json']);
Route::group(['middleware' => 'auth:front'], function () {
    Route::get('/user', function (Request $request) {
        return $request->user();
    });
    Route::apiResource('admin_users'                            , 'App\Http\Controllers\Front\AdminUsersController'                 , ['as'=>'front.admin_users'        , 'parameters' => [ 'admin_users'              => 'admin_users']]);
    Route::apiResource('control_points'                         , 'App\Http\Controllers\Front\ControlPointsController'              , ['as'=>'front.control_points'     ,'parameters' => [ 'control_points'           => 'control_points']]);
    Route::apiResource('cost_centers'                           , 'App\Http\Controllers\Front\CostCentersController'                , ['as'=>'front.cost_centers'       ,'parameters' => [ 'cost_centers'             => 'cost_centers']]);
    Route::apiResource('events'                                 , 'App\Http\Controllers\Front\EventsController'                     , ['as'=>'front.events'             ,'parameters' => [ 'events'                   => 'events']]);
    Route::apiResource('event_expense_natures'                  , 'App\Http\Controllers\Front\EventExpenseNaturesController'        , ['as'=>'front.event_expense_natures','parameters' => [ 'event_expense_natures'    => 'event_expense_natures']]);
    Route::apiResource('event_receipts'                         , 'App\Http\Controllers\Front\EventReceiptsController'              , ['as'=>'front.event_receipts'     ,'parameters' => [ 'event_receipts'           => 'event_receipts']]);
    Route::apiResource('expenses'                               , 'App\Http\Controllers\Front\ExpensesController'                   , ['as'=>'front.expenses'           ,'parameters' => [ 'expenses'                 => 'expenses']]);
    Route::apiResource('transfer'                               , 'App\Http\Controllers\Front\TransferController'                   , ['as'=>'front.transfer'           ,'parameters' => [ 'transfer'                 => 'transfer']]);
    Route::apiResource('expense_natures'                        , 'App\Http\Controllers\Front\ExpenseNaturesController'             , ['as'=>'front.expense_natures'    ,'parameters' => [ 'expense_natures'          => 'expense_natures']]);
    Route::apiResource('expense_receipts'                       , 'App\Http\Controllers\Front\ExpenseReceiptsController'            , ['as'=>'front.expense_receipts'   ,'parameters' => [ 'expense_receipts'         => 'expense_receipts']]);
    Route::apiResource('payment_forms'                          , 'App\Http\Controllers\Front\PaymentFormsController'               , ['as'=>'front.payment_forms'      ,'parameters' => [ 'payment_forms'            => 'payment_forms']]);
    Route::apiResource('subsidiaries'                           , 'App\Http\Controllers\Front\SubsidiariesController'               , ['as'=>'front.subsidiaries'       ,'parameters' => [ 'subsidiaries'             => 'subsidiaries']]);
    Route::apiResource('unit_measurements'                      , 'App\Http\Controllers\Front\UnitMeasurementsController'           , ['as'=>'front.unit_measurements'  ,'parameters' => [ 'unit_measurements'        => 'unit_measurements']]);
    Route::apiResource('users'                                  , 'App\Http\Controllers\Front\UsersController'                      , ['as'=>'front.users'              ,'parameters' => [ 'users'                    => 'users']]);
    Route::apiResource('user_cost_centers'                      , 'App\Http\Controllers\Front\UserCostCentersController'            , ['as'=>'front.user_cost_centers'  ,'parameters' => [ 'user_cost_centers'        => 'user_cost_centers']]);
    Route::apiResource('user_payment_forms'                     , 'App\Http\Controllers\Front\UserPaymentFormsController'           , ['as'=>'front.user_payment_forms','parameters' => [ 'user_payment_forms'        => 'user_payment_forms']]);
    Route::apiResource('user_subsidiaries'                      , 'App\Http\Controllers\Front\UserSubsidiariesController'           , ['as'=>'front.user_subsidiaries'  ,'parameters' => [ 'user_subsidiaries'        => 'user_subsidiaries']]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/'                      , ['as'=>'admin.main_index'              , 'uses'=>'App\Http\Controllers\Admin\IndexController@index']);
Route::get('/termo_privacidade'     , ['as'=>'front.main_termo_privacidade'  , 'uses'=>'App\Http\Controllers\Front\PageController@termo_privacidade']);

resources/views/admin/subsidiaries/_form.blade.php
<div class="form-group col-md-6 {{ $errors->has('subsidiaries.expense_nature_id') ? 'has-error' : '' }}">
    <label for="name">Nome</label>
    <input type="text" 
            id="name" 
            class="form-control" 
            name="subsidiaries[name]" 
            value="{{ old('subsidiaries.name', isset($entity->name) ? $entity->name : '') }}">

    @if($errors->has('subsidiaries.name'))
        <span class="help-block">{{ $errors->first('subsidiaries.name') }}</span>
    @endif
</div>

<div class="form-group col-md-6 {{ $errors->has('subsidiaries.cnpj') ? 'has-error' : '' }}">
    <label for="cnpj">CNPJ</label>
    <input type="text" 
            id="cnpj" 
            class="form-control" 
            name="subsidiaries[cnpj]" 
            value="{{ old('subsidiaries.cnpj', isset($entity->cnpj) ? $entity->cnpj : '') }}">

    @if($errors->has('subsidiaries.cnpj'))
        <span class="help-block">{{ $errors->first('subsidiaries.cnpj') }}</span>
    @endif
</div>

<div class="form-group col-md-6 {{ $errors->has('subsidiaries.internal_app_id') ? 'has-error' : '' }}">
    <label for="internal_app_id">Filial ERP</label>
    <input type="text" 
            id="internal_app_id" 
            class="form-control" 
            name="subsidiaries[internal_app_id]" 
            value="{{ old('subsidiaries.internal_app_id', isset($entity->internal_app_id) ? $entity->internal_app_id : '') }}">

    @if($errors->has('subsidiaries.internal_app_id'))
        <span class="help-block">{{ $errors->first('subsidiaries.internal_app_id') }}</span>
    @endif
</div>

<div class="form-group col-md-6 {{ $errors->has('subsidiaries.active') ? 'has-error' : '' }}">
    <input type="checkbox" 
            id="active" 
            class="" 
            name="subsidiaries[active]" 
            value="1"
            @if(isset($entity->active) && $entity->active == 1)
            checked='checked'
            @endif
            >
            <label for="active">Ativo</label>

    @if($errors->has('subsidiaries.active'))
        <span class="help-block">{{ $errors->first('subsidiaries.active') }}</span>
    @endif
</div>

resources/views/admin/subsidiaries/create.blade.php
@extends('admin.dashboard.page')

@inject('layoutHelper', "\JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper")

@if($layoutHelper->isLayoutTopnavEnabled())
    @php( $def_container_class = 'container' )
@else
    @php( $def_container_class = 'container-fluid' )
@endif

@section('title', config('adminlte.logo'). ' - Filiais')

@section('content_header')
    <h1>Novo Registro</h1>
@stop

@section('content')
  <div class="col-md-12">
    <div class="box box-success">
      <form action="{{ route('admin.subsidiaries.store') }}" method="post">
        <div class="box-body">
          {{csrf_field()}}
          @include('admin.subsidiaries._form')
        </div>
        <div class="box-footer">
          <button class="btn btn-success">Criar</button>
        </div>
      </form>
    </div>
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link rel="stylesheet" href="/js/daterangepicker/daterangepicker.css">
@stop

@section('js')
  <script src="/js/jquery-mask-plugin/jquery.mask.min.js"></script>

  <script>
    $('#cnpj').mask('00.000.000/0000-00', {reverse: true});
  </script>
@stop

resources/views/admin/subsidiaries/edit.blade.php
@extends('admin.dashboard.page')

@inject('layoutHelper', "\JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper")

@if($layoutHelper->isLayoutTopnavEnabled())
    @php( $def_container_class = 'container' )
@else
    @php( $def_container_class = 'container-fluid' )
@endif

@section('title', config('adminlte.logo'). ' - Filiais')

@section('content_header')
    <h1>Editar</h1>
@stop

@section('content')
  <div class="col-md-12">
    <div class="box box-success">
      <form action="{{ route('admin.subsidiaries.update', $entity->id) }}" method="post">
        <div class="box-body">
          {{csrf_field()}}
          <input type="hidden" name="_method" value="put">
          <input type="hidden" name="subsidiaries[id]" value="{{$entity->id}}">
          @include('admin.subsidiaries._form')
        </div>
        <div class="box-footer">
          <button class="btn btn-success">Atualizar</button>
        </div>
      </form>
    </div>
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link rel="stylesheet" href="/js/daterangepicker/daterangepicker.css">
@stop

@section('js')
  <script src="/js/jquery-mask-plugin/jquery.mask.min.js"></script>

  <script>
    $('#cnpj').mask('00.000.000/0000-00', {reverse: true});
  </script>
@stop

resources/views/admin/subsidiaries/index.blade.php
@extends('admin.dashboard.page')

@inject('layoutHelper', "\JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper")

@if($layoutHelper->isLayoutTopnavEnabled())
    @php( $def_container_class = 'container' )
@else
    @php( $def_container_class = 'container-fluid' )
@endif

@section('title', config('adminlte.logo'). ' - Filiais')

@section('content_header')
    <h1>Filiais</h1>
@stop

@section('content')
<div class="col-md-12">
    <div class="box">

    @if ($message = Session::get('message'))
        <div class="alert alert-{{ $message['class'] }} alert-block">
            <button type="button" class="close" data-dismiss="{{ $message['class'] }}">×</button>
            <strong>{{ $message['message'] }}</strong>
        </div>
    @endif
        <!-- /.box-header -->
        <div class="box-body">
            <table  id="table" class="table table-striped table-bordered table-hover">
                <thead><tr>
                    <th style="width: 10px">#</th>
                    <th>Nome</th>
                    <th>CNPJ</th>
                    <th>Filial ERP</th>
                    <th>Ativo</th>
                    <th style="width: 40px">Ações</th>
                </tr></thead>
                <tbody>
                </tbody>
            </table>
            <a class="btn btn-primary pull-right" href="{{route('admin.subsidiaries.create')}}">Novo Registro</a>
        </div>

    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link rel="stylesheet" href="/js/datatables/datatables.min.css">
@stop

@section('js')
<script src="/js/datatables/datatables.min.js"></script>
<script src="/js/datatables/Buttons-1.6.5/js/dataTables.buttons.min.js"></script>
<script src="/js/datatables/Buttons-1.6.5/js/buttons.html5.min.js"></script>
<script src="/js/datatables/Buttons-1.6.5/js/buttons.print.min.js"></script>
<script src="/js/datatables/pdfmake-0.1.36/pdfmake.min.js"></script>
<script src="/js/datatables/pdfmake-0.1.36/vfs_fonts.js"></script>
<script src="/js/datatables/JSZip-2.5.0/jszip.min.js"></script>
<script src="/js/datatables/initialize.js"></script>
<script src="/js/bootstrap-confirmation/bootstrap-confirmation.js"></script>
<script>
		var CSRF_TOKEN;
		var dataTable;
		$(document).ready(function() {
            CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            var ajax_call = "{{ route('admin.subsidiaries.index', ['return_json'=>1])}}";
            carregatDatatable(ajax_call);
		});
		function confirmDelete(id)
		{
            $.ajax({
                url: "{{ route('admin.subsidiaries.destroy','') }}/"+id,
                type: 'DELETE',
                data: {'_token':CSRF_TOKEN},
                success: function(response) {
                    if(response.success == true) {
                        var url = "{{ route('admin.subsidiaries.index')}}";
                        window.location.href = url;
                    }else {
                        alert("Falha ao remover o Registro")
                    }
                },
                error: function(response){
                    alert("Falha ao remover o Registro")
                }
            });
		}
	</script>
@stop