routes/admin.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
This route respond for api/admin*
|
*/

    
Route::middleware('guest')->get('/'             , ['as'=>'admin.index'                              , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@index']);
Route::middleware('guest')->post('/login_json'  , ['as'=>'admin.login.login_json'                   , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@login_json']);
Route::middleware('guest')->post('/login'       , ['as'=>'admin.login.login'                        , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@login']);
Route::middleware('guest')->get('/logout'       , ['as'=>'admin.login.logout'                      , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@logout']);
Route::middleware('guest')->get('/form_login'   , ['as'=>'admin.login.form_login'                   , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@index']);
Route::group(['middleware' => 'auth:admin'], function () {
    Route::get('/admin_users/edit/{admin_users}'                        , ['as'=>'admin.admin_users.edit'           , 'uses'=>'App\Http\Controllers\Admin\AdminUsersController@edit']);
    Route::get('/admin_users/create'                                    , ['as'=>'admin.admin_users.create'         , 'uses'=>'App\Http\Controllers\Admin\AdminUsersController@create']);
    Route::apiResource('admin_users'                                    , 'App\Http\Controllers\Admin\AdminUsersController'                 , ['as' => 'admin', 'parameters' => [ 'admin_users'              => 'admin_users']]);
    
    Route::get('/control_points/edit/{control_points}'                  , ['as'=>'admin.control_points.edit'           , 'uses'=>'App\Http\Controllers\Admin\ControlPointsController@edit']);
    Route::get('/control_points/create'                                 , ['as'=>'admin.control_points.create'         , 'uses'=>'App\Http\Controllers\Admin\ControlPointsController@create']);
    Route::apiResource('control_points'                                 , 'App\Http\Controllers\Admin\ControlPointsController'              , ['as' => 'admin', 'parameters' => [ 'control_points'           => 'control_points']]);
    
    Route::get('/cost_centers/edit/{cost_centers}'                      , ['as'=>'admin.cost_centers.edit'           , 'uses'=>'App\Http\Controllers\Admin\CostCentersController@edit']);
    Route::get('/cost_centers/create'                                   , ['as'=>'admin.cost_centers.create'         , 'uses'=>'App\Http\Controllers\Admin\CostCentersController@create']);
    Route::apiResource('cost_centers'                                   , 'App\Http\Controllers\Admin\CostCentersController'                , ['as' => 'admin', 'parameters' => [ 'cost_centers'             => 'cost_centers']]);
    
    Route::get('/departaments/edit/{departaments}'                      , ['as'=>'admin.departaments.edit'           , 'uses'=>'App\Http\Controllers\Admin\DepartamentsController@edit']);
    Route::get('/departaments/create'                                   , ['as'=>'admin.departaments.create'         , 'uses'=>'App\Http\Controllers\Admin\DepartamentsController@create']);
    Route::apiResource('departaments'                                   , 'App\Http\Controllers\Admin\DepartamentsController'                , ['as' => 'admin', 'parameters' => [ 'departaments'             => 'departaments']]);

    Route::get('/events/edit/{events}'                                  , ['as'=>'admin.events.edit'           , 'uses'=>'App\Http\Controllers\Admin\EventsController@edit']);
    Route::get('/events/create'                                         , ['as'=>'admin.events.create'         , 'uses'=>'App\Http\Controllers\Admin\EventsController@create']);
    Route::apiResource('events'                                         , 'App\Http\Controllers\Admin\EventsController'                     , ['as' => 'admin', 'parameters' => [ 'events'                   => 'events']]);
    
    Route::get('/event_expense_natures/edit/{event_expense_natures}'    , ['as'=>'admin.event_expense_natures.edit'           , 'uses'=>'App\Http\Controllers\Admin\EventExpenseNaturesController@edit']);
    Route::get('/event_expense_natures/create'                          , ['as'=>'admin.event_expense_natures.create'         , 'uses'=>'App\Http\Controllers\Admin\EventExpenseNaturesController@create']);
    Route::apiResource('event_expense_natures'                          , 'App\Http\Controllers\Admin\EventExpenseNaturesController'        , ['as' => 'admin', 'parameters' => [ 'event_expense_natures'    => 'event_expense_natures']]);
    
    Route::get('/event_receipts/edit/{event_receipts}'                  , ['as'=>'admin.event_receipts.edit'           , 'uses'=>'App\Http\Controllers\Admin\EventReceiptsController@edit']);
    Route::get('/event_receipts/create'                                 , ['as'=>'admin.event_receipts.create'         , 'uses'=>'App\Http\Controllers\Admin\EventReceiptsController@create']);
    Route::apiResource('event_receipts'                                 , 'App\Http\Controllers\Admin\EventReceiptsController'              , ['as' => 'admin', 'parameters' => [ 'event_receipts'           => 'event_receipts']]);
    
    Route::get('/expenses/edit/{expenses}'                              , ['as'=>'admin.expenses.edit'           , 'uses'=>'App\Http\Controllers\Admin\ExpensesController@edit']);
    Route::get('/expenses/create'                                       , ['as'=>'admin.expenses.create'         , 'uses'=>'App\Http\Controllers\Admin\ExpensesController@create']);
    Route::apiResource('expenses'                                       , 'App\Http\Controllers\Admin\ExpensesController'                   , ['as' => 'admin', 'parameters' => [ 'expenses'                 => 'expenses']]);
    
    Route::get('/expense_natures/edit/{expense_natures}'                , ['as'=>'admin.expense_natures.edit'           , 'uses'=>'App\Http\Controllers\Admin\ExpenseNaturesController@edit']);
    Route::get('/expense_natures/create'                                , ['as'=>'admin.expense_natures.create'         , 'uses'=>'App\Http\Controllers\Admin\ExpenseNaturesController@create']);
    Route::apiResource('expense_natures'                                , 'App\Http\Controllers\Admin\ExpenseNaturesController'             , ['as' => 'admin', 'parameters' => [ 'expense_natures'          => 'expense_natures']]);
    
    Route::get('/expense_receipts/edit/{expense_receipts}'              , ['as'=>'admin.expense_receipts.edit'           , 'uses'=>'App\Http\Controllers\Admin\ExpenseReceiptsController@edit']);
    Route::get('/expense_receipts/create'                               , ['as'=>'admin.expense_receipts.create'         , 'uses'=>'App\Http\Controllers\Admin\ExpenseReceiptsController@create']);
    Route::apiResource('expense_receipts'                               , 'App\Http\Controllers\Admin\ExpenseReceiptsController'            , ['as' => 'admin', 'parameters' => [ 'expense_receipts'         => 'expense_receipts']]);
    
    Route::get('/payment_forms/edit/{payment_forms}'                    , ['as'=>'admin.payment_forms.edit'           , 'uses'=>'App\Http\Controllers\Admin\PaymentFormsController@edit']);
    Route::get('/payment_forms/create'                                  , ['as'=>'admin.payment_forms.create'         , 'uses'=>'App\Http\Controllers\Admin\PaymentFormsController@create']);
    Route::post('/payment_forms/index_manager'                          , ['as'=>'admin.payment_forms.index_manager'  , 'uses'=>'App\Http\Controllers\Admin\PaymentFormsController@index_manager']);
    Route::apiResource('payment_forms'                                  , 'App\Http\Controllers\Admin\PaymentFormsController'               , ['as' => 'admin', 'parameters' => [ 'payment_forms'            => 'payment_forms']]);
    
    Route::get('/subsidiaries/edit/{subsidiaries}'                      , ['as'=>'admin.subsidiaries.edit'           , 'uses'=>'App\Http\Controllers\Admin\SubsidiariesController@edit']);
    Route::get('/subsidiaries/create'                                   , ['as'=>'admin.subsidiaries.create'         , 'uses'=>'App\Http\Controllers\Admin\SubsidiariesController@create']);
    Route::apiResource('subsidiaries'                                   , 'App\Http\Controllers\Admin\SubsidiariesController'               , ['as' => 'admin', 'parameters' => [ 'subsidiaries'             => 'subsidiaries']]);
    
    Route::get('/unit_measurements/edit/{unit_measurements}'            , ['as'=>'admin.unit_measurements.edit'           , 'uses'=>'App\Http\Controllers\Admin\UnitMeasurementsController@edit']);
    Route::get('/unit_measurements/create'                              , ['as'=>'admin.unit_measurements.create'         , 'uses'=>'App\Http\Controllers\Admin\UnitMeasurementsController@create']);
    Route::apiResource('unit_measurements'                              , 'App\Http\Controllers\Admin\UnitMeasurementsController'           , ['as' => 'admin', 'parameters' => [ 'unit_measurements'        => 'unit_measurements']]);
    
    Route::get('/users/edit/{users}'                            , ['as'=>'admin.users.edit'           , 'uses'=>'App\Http\Controllers\Admin\UsersController@edit']);
    Route::get('/users/create'                                  , ['as'=>'admin.users.create'         , 'uses'=>'App\Http\Controllers\Admin\UsersController@create']);
    Route::apiResource('users'                                  , 'App\Http\Controllers\Admin\UsersController'                      , ['as' => 'admin', 'parameters' => [ 'users'                    => 'users']]);

routes/front.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/
Route::middleware('guest')->post('/login_json', ['as'=>'front.login.login_json'                  , 'uses'=>'App\Http\Controllers\Auth\LoginUsersController@login_json']);
Route::group(['middleware' => 'auth:front'], function () {
    Route::get('/user', function (Request $request) {
        return $request->user();
    });
    Route::apiResource('admin_users'                            , 'App\Http\Controllers\Front\AdminUsersController'                 , ['as'=>'front.admin_users'        , 'parameters' => [ 'admin_users'              => 'admin_users']]);
    Route::apiResource('control_points'                         , 'App\Http\Controllers\Front\ControlPointsController'              , ['as'=>'front.control_points'     ,'parameters' => [ 'control_points'           => 'control_points']]);
    Route::apiResource('cost_centers'                           , 'App\Http\Controllers\Front\CostCentersController'                , ['as'=>'front.cost_centers'       ,'parameters' => [ 'cost_centers'             => 'cost_centers']]);
    Route::apiResource('events'                                 , 'App\Http\Controllers\Front\EventsController'                     , ['as'=>'front.events'             ,'parameters' => [ 'events'                   => 'events']]);
    Route::apiResource('event_expense_natures'                  , 'App\Http\Controllers\Front\EventExpenseNaturesController'        , ['as'=>'front.event_expense_natures','parameters' => [ 'event_expense_natures'    => 'event_expense_natures']]);
    Route::apiResource('event_receipts'                         , 'App\Http\Controllers\Front\EventReceiptsController'              , ['as'=>'front.event_receipts'     ,'parameters' => [ 'event_receipts'           => 'event_receipts']]);
    Route::apiResource('expenses'                               , 'App\Http\Controllers\Front\ExpensesController'                   , ['as'=>'front.expenses'           ,'parameters' => [ 'expenses'                 => 'expenses']]);
    Route::apiResource('transfer'                               , 'App\Http\Controllers\Front\TransferController'                   , ['as'=>'front.transfer'           ,'parameters' => [ 'transfer'                 => 'transfer']]);
    Route::apiResource('expense_natures'                        , 'App\Http\Controllers\Front\ExpenseNaturesController'             , ['as'=>'front.expense_natures'    ,'parameters' => [ 'expense_natures'          => 'expense_natures']]);
    Route::apiResource('expense_receipts'                       , 'App\Http\Controllers\Front\ExpenseReceiptsController'            , ['as'=>'front.expense_receipts'   ,'parameters' => [ 'expense_receipts'         => 'expense_receipts']]);
    Route::apiResource('payment_forms'                          , 'App\Http\Controllers\Front\PaymentFormsController'               , ['as'=>'front.payment_forms'      ,'parameters' => [ 'payment_forms'            => 'payment_forms']]);
    Route::apiResource('subsidiaries'                           , 'App\Http\Controllers\Front\SubsidiariesController'               , ['as'=>'front.subsidiaries'       ,'parameters' => [ 'subsidiaries'             => 'subsidiaries']]);
    Route::apiResource('unit_measurements'                      , 'App\Http\Controllers\Front\UnitMeasurementsController'           , ['as'=>'front.unit_measurements'  ,'parameters' => [ 'unit_measurements'        => 'unit_measurements']]);
    Route::apiResource('users'                                  , 'App\Http\Controllers\Front\UsersController'                      , ['as'=>'front.users'              ,'parameters' => [ 'users'                    => 'users']]);
    Route::apiResource('user_cost_centers'                      , 'App\Http\Controllers\Front\UserCostCentersController'            , ['as'=>'front.user_cost_centers'  ,'parameters' => [ 'user_cost_centers'        => 'user_cost_centers']]);
    Route::apiResource('user_payment_forms'                     , 'App\Http\Controllers\Front\UserPaymentFormsController'           , ['as'=>'front.user_payment_forms','parameters' => [ 'user_payment_forms'        => 'user_payment_forms']]);
    Route::apiResource('user_subsidiaries'                      , 'App\Http\Controllers\Front\UserSubsidiariesController'           , ['as'=>'front.user_subsidiaries'  ,'parameters' => [ 'user_subsidiaries'        => 'user_subsidiaries']]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/'                      , ['as'=>'admin.main_index'              , 'uses'=>'App\Http\Controllers\Admin\IndexController@index']);
Route::get('/termo_privacidade'     , ['as'=>'front.main_termo_privacidade'  , 'uses'=>'App\Http\Controllers\Front\PageController@termo_privacidade']);

app/Models/Admin/AdminUsers.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $email_verified_at
 * @property string $password
 * @property string $api_token
 * @property string $remember_token
 * @property string $created_at
 * @property string $updated_at
 */
class AdminUsers extends Authenticatable
{
    use Notifiable;
    protected $guard = 'admin';
    /**
     * The "type" of the auto-incrementing ID.
     * 
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * @var array
     */
    protected $fillable = ['name', 'email', 'email_verified_at', 'password', 'remember_token', 'created_at', 'updated_at'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function scopeFilter($query, $params)
    {
        if(is_array($params)){
            foreach($params as $key => $data){
                if(in_array($key, $this->fillable) && trim($params[$key] !== '')){
                    $query->where($key, 'LIKE', trim($params[$key]) . '%');
                }
            }
        }
        return $query;
    }
}

resources/views/admin/admin_users/_form.blade.php
<div class="form-group col-md-6 {{ $errors->has('admin_users.name') ? 'has-error' : '' }}">
    <label for="nome">Nome</label>
    <input type="text" 
            id="name" 
            class="form-control" 
            name="admin_users[name]" 
            value="{{ old('admin_users.name', isset($entity->name) ? $entity->name : '') }}">

    @if($errors->has('admin_users.name'))
        <span class="help-block">{{ $errors->first('admin_users.name') }}</span>
    @endif
</div>

<div class="form-group col-md-6 {{ $errors->has('admin_users.email') ? 'has-error' : '' }}">
    <label for="email">Email</label>
    <input type="text" 
            id="email" 
            class="form-control" 
            name="admin_users[email]" 
            value="{{ old('admin_users.email', isset($entity->email) ? $entity->email : '') }}">

    @if($errors->has('admin_users.email'))
        <span class="help-block">{{ $errors->first('admin_users.email') }}</span>
    @endif
</div>
<div class="form-group col-md-6 {{ $errors->has('admin_users.password') ? 'has-error' : '' }}">
    <label for="password">Password</label>
    <input type="text" 
            id="password" 
            class="form-control" 
            name="admin_users[password]" 
            value="{{ old('admin_users.password', '') }}">

    @if($errors->has('admin_users.password'))
        <span class="help-block">{{ $errors->first('admin_users.password') }}</span>
    @endif
</div>
<div class="form-group col-md-6 {{ $errors->has('admin_users.password_confirmation') ? 'has-error' : '' }}">
    <label for="password_confirmation">Password Confirmation</label>
    <input type="text" 
            id="password_confirmation" 
            class="form-control" 
            name="admin_users[password_confirmation]" 
            value="{{ old('admin_users.password_confirmation', '') }}">

    @if($errors->has('admin_users.password_confirmation'))
        <span class="help-block">{{ $errors->first('admin_users.password_confirmation') }}</span>
    @endif
</div>

resources/views/admin/admin_users/create.blade.php
@extends('admin.dashboard.page')

@inject('layoutHelper', "\JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper")

@if($layoutHelper->isLayoutTopnavEnabled())
    @php( $def_container_class = 'container' )
@else
    @php( $def_container_class = 'container-fluid' )
@endif

@section('title', config('adminlte.logo'). ' - Usuários Administrativos')

@section('content_header')
    <h1>Novo</h1>
@stop

@section('content')
  <div class="col-md-12">
    <div class="box box-success">
      <form action="{{ route('admin.admin_users.store') }}" method="post">
        <div class="box-body">
          {{csrf_field()}}
          @include('admin.admin_users._form')
        </div>
        <div class="box-footer">
          <button class="btn btn-success">Criar</button>
        </div>
      </form>
    </div>
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/admin/admin_users/edit.blade.php
@extends('admin.dashboard.page')

@inject('layoutHelper', "\JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper")

@if($layoutHelper->isLayoutTopnavEnabled())
    @php( $def_container_class = 'container' )
@else
    @php( $def_container_class = 'container-fluid' )
@endif

@section('title', config('adminlte.logo'). ' - Usuários Administrativos')

@section('content_header')
    <h1>Editar</h1>
@stop

@section('content')
  <div class="col-md-12">
    <div class="box box-success">
      <form action="{{ route('admin.admin_users.update', $entity->id) }}" method="post">
        <div class="box-body">
          {{csrf_field()}}
          <input type="hidden" name="_method" value="put">
          @include('admin.admin_users._form')
        </div>
        <div class="box-footer">
          <button class="btn btn-success">Atualizar</button>
        </div>
      </form>
    </div>
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/admin_users/index.blade.php
@extends('admin.dashboard.page')

@inject('layoutHelper', "\JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper")

@if($layoutHelper->isLayoutTopnavEnabled())
    @php( $def_container_class = 'container' )
@else
    @php( $def_container_class = 'container-fluid' )
@endif

@section('title', config('adminlte.logo'). ' - Usuários Administrativos')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
<div class="col-md-12">
    <div class="box">

    @if ($message = Session::get('message'))
        <div class="alert alert-{{ $message['class'] }} alert-block">
            <button type="button" class="close" data-dismiss="{{ $message['class'] }}">×</button>
            <strong>{{ $message['message'] }}</strong>
        </div>
    @endif
        <!-- /.box-header -->
        <div class="box-body">
            <table  id="table" class="table table-striped table-bordered table-hover">
                <thead><tr>
                    <th style="width: 10px">#</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th style="width: 40px">Label</th>
                </tr></thead>
                <tbody>
                @foreach($entities as $entity)
                    <tr>
                        <td>#{{ $entity->id }}</td>
                        <td>{{ $entity->name }}</td>
                        <td>{{ $entity->email }}</td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-default" href="{{ route('admin.admin_users.edit',$entity->id) }}"><i class="fa fa-fw fa-edit"> </i>{{ __('Editar') }}</a>
                                <a class="btn btn-default" data-confirmation-event="confirmDelete" data-toggle="confirmation" href="javascript: confirmDelete('{{ $entity->id }}')"><i class="fa fa-fw fa-trash"></i>{{ __('Remover') }}</a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <a class="btn btn-primary pull-right" href="{{route('admin.admin_users.create')}}">Novo Registro</a>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
            <ul class="pagination pagination-sm no-margin pull-right">
            <li><a href="#">«</a></li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">»</a></li>
            </ul>
        </div>
        </div>
        <!-- /.box -->


    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link rel="stylesheet" href="/js/datatables/datatables.min.css">
@stop

@section('js')
<script src="/js/datatables/datatables.min.js"></script>
<script src="/js/datatables/Buttons-1.6.5/js/dataTables.buttons.min.js"></script>
<script src="/js/datatables/Buttons-1.6.5/js/buttons.html5.min.js"></script>
<script src="/js/datatables/Buttons-1.6.5/js/buttons.print.min.js"></script>
<script src="/js/datatables/pdfmake-0.1.36/pdfmake.min.js"></script>
<script src="/js/datatables/pdfmake-0.1.36/vfs_fonts.js"></script>
<script src="/js/datatables/JSZip-2.5.0/jszip.min.js"></script>
<script src="/js/datatables/initialize.js"></script>
<script src="/js/bootstrap-confirmation/bootstrap-confirmation.js"></script>
<script>
		var CSRF_TOKEN;
		var dataTable;
		$(document).ready(function() {
            CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            var ajax_call = "{{ route('admin.cost_centers.index', ['return_json'=>1])}}";
            carregatDatatable(ajax_call);
		});
		function confirmDelete(id)
		{
            $.ajax({
                url: "{{ route('admin.admin_users.destroy','') }}/"+id,
                type: 'DELETE',
                data: {'_token':CSRF_TOKEN},
                success: function(response) {
                    if(response.success == true) {
                        var url = "{{ route('admin.admin_users.index')}}";
                        window.location.href = url;
                    }else {
                        alert("Falha ao remover o Registro")
                    }
                },
                error: function(response){
                    alert("Falha ao remover o Registro")
                }
            });
		}
        $('[data-toggle=confirmation]').confirmation({
        rootSelector: '[data-toggle=confirmation]',
        title: 'Deseja remover o registro?',
        btnOkLabel:"Sim",
        btnCancelLabel:"Não"
        });
	</script>
@stop