routes/admin.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
This route respond for api/admin*
|
*/

    
Route::middleware('guest')->get('/'             , ['as'=>'admin.index'                              , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@index']);
Route::middleware('guest')->post('/login_json'  , ['as'=>'admin.login.login_json'                   , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@login_json']);
Route::middleware('guest')->post('/login'       , ['as'=>'admin.login.login'                        , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@login']);
Route::middleware('guest')->get('/logout'       , ['as'=>'admin.login.logout'                      , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@logout']);
Route::middleware('guest')->get('/form_login'   , ['as'=>'admin.login.form_login'                   , 'uses'=>'App\Http\Controllers\Auth\LoginAdminController@index']);
Route::group(['middleware' => 'auth:admin'], function () {
    Route::get('/admin_users/edit/{admin_users}'                        , ['as'=>'admin.admin_users.edit'           , 'uses'=>'App\Http\Controllers\Admin\AdminUsersController@edit']);
    Route::get('/admin_users/create'                                    , ['as'=>'admin.admin_users.create'         , 'uses'=>'App\Http\Controllers\Admin\AdminUsersController@create']);
    Route::apiResource('admin_users'                                    , 'App\Http\Controllers\Admin\AdminUsersController'                 , ['as' => 'admin', 'parameters' => [ 'admin_users'              => 'admin_users']]);
    
    Route::get('/control_points/edit/{control_points}'                  , ['as'=>'admin.control_points.edit'           , 'uses'=>'App\Http\Controllers\Admin\ControlPointsController@edit']);
    Route::get('/control_points/create'                                 , ['as'=>'admin.control_points.create'         , 'uses'=>'App\Http\Controllers\Admin\ControlPointsController@create']);
    Route::apiResource('control_points'                                 , 'App\Http\Controllers\Admin\ControlPointsController'              , ['as' => 'admin', 'parameters' => [ 'control_points'           => 'control_points']]);
    
    Route::get('/cost_centers/edit/{cost_centers}'                      , ['as'=>'admin.cost_centers.edit'           , 'uses'=>'App\Http\Controllers\Admin\CostCentersController@edit']);
    Route::get('/cost_centers/create'                                   , ['as'=>'admin.cost_centers.create'         , 'uses'=>'App\Http\Controllers\Admin\CostCentersController@create']);
    Route::apiResource('cost_centers'                                   , 'App\Http\Controllers\Admin\CostCentersController'                , ['as' => 'admin', 'parameters' => [ 'cost_centers'             => 'cost_centers']]);
    
    Route::get('/departaments/edit/{departaments}'                      , ['as'=>'admin.departaments.edit'           , 'uses'=>'App\Http\Controllers\Admin\DepartamentsController@edit']);
    Route::get('/departaments/create'                                   , ['as'=>'admin.departaments.create'         , 'uses'=>'App\Http\Controllers\Admin\DepartamentsController@create']);
    Route::apiResource('departaments'                                   , 'App\Http\Controllers\Admin\DepartamentsController'                , ['as' => 'admin', 'parameters' => [ 'departaments'             => 'departaments']]);

    Route::get('/events/edit/{events}'                                  , ['as'=>'admin.events.edit'           , 'uses'=>'App\Http\Controllers\Admin\EventsController@edit']);
    Route::get('/events/create'                                         , ['as'=>'admin.events.create'         , 'uses'=>'App\Http\Controllers\Admin\EventsController@create']);
    Route::apiResource('events'                                         , 'App\Http\Controllers\Admin\EventsController'                     , ['as' => 'admin', 'parameters' => [ 'events'                   => 'events']]);
    
    Route::get('/event_expense_natures/edit/{event_expense_natures}'    , ['as'=>'admin.event_expense_natures.edit'           , 'uses'=>'App\Http\Controllers\Admin\EventExpenseNaturesController@edit']);
    Route::get('/event_expense_natures/create'                          , ['as'=>'admin.event_expense_natures.create'         , 'uses'=>'App\Http\Controllers\Admin\EventExpenseNaturesController@create']);
    Route::apiResource('event_expense_natures'                          , 'App\Http\Controllers\Admin\EventExpenseNaturesController'        , ['as' => 'admin', 'parameters' => [ 'event_expense_natures'    => 'event_expense_natures']]);
    
    Route::get('/event_receipts/edit/{event_receipts}'                  , ['as'=>'admin.event_receipts.edit'           , 'uses'=>'App\Http\Controllers\Admin\EventReceiptsController@edit']);
    Route::get('/event_receipts/create'                                 , ['as'=>'admin.event_receipts.create'         , 'uses'=>'App\Http\Controllers\Admin\EventReceiptsController@create']);
    Route::apiResource('event_receipts'                                 , 'App\Http\Controllers\Admin\EventReceiptsController'              , ['as' => 'admin', 'parameters' => [ 'event_receipts'           => 'event_receipts']]);
    
    Route::get('/expenses/edit/{expenses}'                              , ['as'=>'admin.expenses.edit'           , 'uses'=>'App\Http\Controllers\Admin\ExpensesController@edit']);
    Route::get('/expenses/create'                                       , ['as'=>'admin.expenses.create'         , 'uses'=>'App\Http\Controllers\Admin\ExpensesController@create']);
    Route::apiResource('expenses'                                       , 'App\Http\Controllers\Admin\ExpensesController'                   , ['as' => 'admin', 'parameters' => [ 'expenses'                 => 'expenses']]);
    
    Route::get('/expense_natures/edit/{expense_natures}'                , ['as'=>'admin.expense_natures.edit'           , 'uses'=>'App\Http\Controllers\Admin\ExpenseNaturesController@edit']);
    Route::get('/expense_natures/create'                                , ['as'=>'admin.expense_natures.create'         , 'uses'=>'App\Http\Controllers\Admin\ExpenseNaturesController@create']);
    Route::apiResource('expense_natures'                                , 'App\Http\Controllers\Admin\ExpenseNaturesController'             , ['as' => 'admin', 'parameters' => [ 'expense_natures'          => 'expense_natures']]);
    
    Route::get('/expense_receipts/edit/{expense_receipts}'              , ['as'=>'admin.expense_receipts.edit'           , 'uses'=>'App\Http\Controllers\Admin\ExpenseReceiptsController@edit']);
    Route::get('/expense_receipts/create'                               , ['as'=>'admin.expense_receipts.create'         , 'uses'=>'App\Http\Controllers\Admin\ExpenseReceiptsController@create']);
    Route::apiResource('expense_receipts'                               , 'App\Http\Controllers\Admin\ExpenseReceiptsController'            , ['as' => 'admin', 'parameters' => [ 'expense_receipts'         => 'expense_receipts']]);
    
    Route::get('/payment_forms/edit/{payment_forms}'                    , ['as'=>'admin.payment_forms.edit'           , 'uses'=>'App\Http\Controllers\Admin\PaymentFormsController@edit']);
    Route::get('/payment_forms/create'                                  , ['as'=>'admin.payment_forms.create'         , 'uses'=>'App\Http\Controllers\Admin\PaymentFormsController@create']);
    Route::post('/payment_forms/index_manager'                          , ['as'=>'admin.payment_forms.index_manager'  , 'uses'=>'App\Http\Controllers\Admin\PaymentFormsController@index_manager']);
    Route::apiResource('payment_forms'                                  , 'App\Http\Controllers\Admin\PaymentFormsController'               , ['as' => 'admin', 'parameters' => [ 'payment_forms'            => 'payment_forms']]);
    
    Route::get('/subsidiaries/edit/{subsidiaries}'                      , ['as'=>'admin.subsidiaries.edit'           , 'uses'=>'App\Http\Controllers\Admin\SubsidiariesController@edit']);
    Route::get('/subsidiaries/create'                                   , ['as'=>'admin.subsidiaries.create'         , 'uses'=>'App\Http\Controllers\Admin\SubsidiariesController@create']);
    Route::apiResource('subsidiaries'                                   , 'App\Http\Controllers\Admin\SubsidiariesController'               , ['as' => 'admin', 'parameters' => [ 'subsidiaries'             => 'subsidiaries']]);
    
    Route::get('/unit_measurements/edit/{unit_measurements}'            , ['as'=>'admin.unit_measurements.edit'           , 'uses'=>'App\Http\Controllers\Admin\UnitMeasurementsController@edit']);
    Route::get('/unit_measurements/create'                              , ['as'=>'admin.unit_measurements.create'         , 'uses'=>'App\Http\Controllers\Admin\UnitMeasurementsController@create']);
    Route::apiResource('unit_measurements'                              , 'App\Http\Controllers\Admin\UnitMeasurementsController'           , ['as' => 'admin', 'parameters' => [ 'unit_measurements'        => 'unit_measurements']]);
    
    Route::get('/users/edit/{users}'                            , ['as'=>'admin.users.edit'           , 'uses'=>'App\Http\Controllers\Admin\UsersController@edit']);
    Route::get('/users/create'                                  , ['as'=>'admin.users.create'         , 'uses'=>'App\Http\Controllers\Admin\UsersController@create']);
    Route::apiResource('users'                                  , 'App\Http\Controllers\Admin\UsersController'                      , ['as' => 'admin', 'parameters' => [ 'users'                    => 'users']]);

routes/front.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/
Route::middleware('guest')->post('/login_json', ['as'=>'front.login.login_json'                  , 'uses'=>'App\Http\Controllers\Auth\LoginUsersController@login_json']);
Route::group(['middleware' => 'auth:front'], function () {
    Route::get('/user', function (Request $request) {
        return $request->user();
    });
    Route::apiResource('admin_users'                            , 'App\Http\Controllers\Front\AdminUsersController'                 , ['as'=>'front.admin_users'        , 'parameters' => [ 'admin_users'              => 'admin_users']]);
    Route::apiResource('control_points'                         , 'App\Http\Controllers\Front\ControlPointsController'              , ['as'=>'front.control_points'     ,'parameters' => [ 'control_points'           => 'control_points']]);
    Route::apiResource('cost_centers'                           , 'App\Http\Controllers\Front\CostCentersController'                , ['as'=>'front.cost_centers'       ,'parameters' => [ 'cost_centers'             => 'cost_centers']]);
    Route::apiResource('events'                                 , 'App\Http\Controllers\Front\EventsController'                     , ['as'=>'front.events'             ,'parameters' => [ 'events'                   => 'events']]);
    Route::apiResource('event_expense_natures'                  , 'App\Http\Controllers\Front\EventExpenseNaturesController'        , ['as'=>'front.event_expense_natures','parameters' => [ 'event_expense_natures'    => 'event_expense_natures']]);
    Route::apiResource('event_receipts'                         , 'App\Http\Controllers\Front\EventReceiptsController'              , ['as'=>'front.event_receipts'     ,'parameters' => [ 'event_receipts'           => 'event_receipts']]);
    Route::apiResource('expenses'                               , 'App\Http\Controllers\Front\ExpensesController'                   , ['as'=>'front.expenses'           ,'parameters' => [ 'expenses'                 => 'expenses']]);
    Route::apiResource('transfer'                               , 'App\Http\Controllers\Front\TransferController'                   , ['as'=>'front.transfer'           ,'parameters' => [ 'transfer'                 => 'transfer']]);
    Route::apiResource('expense_natures'                        , 'App\Http\Controllers\Front\ExpenseNaturesController'             , ['as'=>'front.expense_natures'    ,'parameters' => [ 'expense_natures'          => 'expense_natures']]);
    Route::apiResource('expense_receipts'                       , 'App\Http\Controllers\Front\ExpenseReceiptsController'            , ['as'=>'front.expense_receipts'   ,'parameters' => [ 'expense_receipts'         => 'expense_receipts']]);
    Route::apiResource('payment_forms'                          , 'App\Http\Controllers\Front\PaymentFormsController'               , ['as'=>'front.payment_forms'      ,'parameters' => [ 'payment_forms'            => 'payment_forms']]);
    Route::apiResource('subsidiaries'                           , 'App\Http\Controllers\Front\SubsidiariesController'               , ['as'=>'front.subsidiaries'       ,'parameters' => [ 'subsidiaries'             => 'subsidiaries']]);
    Route::apiResource('unit_measurements'                      , 'App\Http\Controllers\Front\UnitMeasurementsController'           , ['as'=>'front.unit_measurements'  ,'parameters' => [ 'unit_measurements'        => 'unit_measurements']]);
    Route::apiResource('users'                                  , 'App\Http\Controllers\Front\UsersController'                      , ['as'=>'front.users'              ,'parameters' => [ 'users'                    => 'users']]);
    Route::apiResource('user_cost_centers'                      , 'App\Http\Controllers\Front\UserCostCentersController'            , ['as'=>'front.user_cost_centers'  ,'parameters' => [ 'user_cost_centers'        => 'user_cost_centers']]);
    Route::apiResource('user_payment_forms'                     , 'App\Http\Controllers\Front\UserPaymentFormsController'           , ['as'=>'front.user_payment_forms','parameters' => [ 'user_payment_forms'        => 'user_payment_forms']]);
    Route::apiResource('user_subsidiaries'                      , 'App\Http\Controllers\Front\UserSubsidiariesController'           , ['as'=>'front.user_subsidiaries'  ,'parameters' => [ 'user_subsidiaries'        => 'user_subsidiaries']]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/'                      , ['as'=>'admin.main_index'              , 'uses'=>'App\Http\Controllers\Admin\IndexController@index']);
Route::get('/termo_privacidade'     , ['as'=>'front.main_termo_privacidade'  , 'uses'=>'App\Http\Controllers\Front\PageController@termo_privacidade']);

resources/views/admin/menu/left-sidebar.blade.php
<aside class="main-sidebar {{ config('adminlte.classes_sidebar', 'sidebar-dark-primary elevation-4') }}">

    <a href="{{ route('admin.dashboard')}}"
        @if($layoutHelper->isLayoutTopnavEnabled())
            class="navbar-brand {{ config('adminlte.classes_brand') }}"
        @else
            class="brand-link {{ config('adminlte.classes_brand') }}"
        @endif>

        {{-- Small brand logo --}}
        <img src="{{ asset(config('adminlte.logo_img', 'vendor/adminlte/dist/img/AdminLTELogo.png')) }}"
            alt="{{ config('adminlte.logo_img_alt', 'AdminLTE') }}"
            class="{{ config('adminlte.logo_img_class', 'brand-image img-circle elevation-3') }}"
            style="opacity:.8">

        {{-- Brand text --}}
        <span class="brand-text font-weight-light {{ config('adminlte.classes_brand_text') }}">
            {!! config('adminlte.logo', '<b>Admin</b>LTE') !!}
        </span>

    </a>

    {{-- Sidebar menu --}}
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column {{ config('adminlte.classes_sidebar_nav', '') }}"
                data-widget="treeview" role="menu"
                @if(config('adminlte.sidebar_nav_animation_speed') != 300)
                    data-animation-speed="{{ config('adminlte.sidebar_nav_animation_speed') }}"
                @endif
                @if(!config('adminlte.sidebar_nav_accordion'))
                    data-accordion="false"
                @endif>

                <li class="nav-header ">
                    Geral
                </li>
                @if(securityAccess(App\Models\General\SystemModules::$SM_USERS_INDEX))
                <li class="nav-item">
                    <a class="nav-link  " href="{{ route('admin.users.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Gestor</p>
                    </a>
                </li>
                @endif
                @if(securityAccess(App\Models\General\SystemModules::$SM_DEPARTAMENTS_INDEX))
                <li class="nav-item">
                    <a class="nav-link  " href="{{ route('admin.departaments.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Departamento</p>
                    </a>
                </li>
                @endif
                @if(securityAccess(App\Models\General\SystemModules::$SM_CONTROL_POINTS_INDEX))
                <li class="nav-item">
                    <a class="nav-link  " href="{{ route('admin.control_points.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Check-in</p>
                    </a>
                </li>
                @endif
                @if(securityAccess(App\Models\General\SystemModules::$SM_COST_CENTERS_INDEX))
                <li class="nav-item">
                    <a class="nav-link  " href="{{ route('admin.cost_centers.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Centro de Custo</p>
                    </a>
                </li>
                @endif
                @if(securityAccess(App\Models\General\SystemModules::$SM_UNIT_MEASUREMENTS_INDEX))
                <li class="nav-item" style="display:none;">
                    <a class="nav-link  " href="{{ route('admin.unit_measurements.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Unidade de Medida</p>
                    </a>
                </li>
                @endif
                @if(securityAccess(App\Models\General\SystemModules::$SM_EXPENSE_NATURES_INDEX))
                <li class="nav-item">
                    <a class="nav-link  " href="{{ route('admin.expense_natures.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Natureza Gasto</p>
                    </a>
                </li>
                @endif
                @if(securityAccess(App\Models\General\SystemModules::$SM_PAYMENT_FORMS_INDEX))
                <li class="nav-item">
                    <a class="nav-link  " href="{{ route('admin.payment_forms.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Contas</p>
                    </a>
                </li>
                @endif
                @if(securityAccess(App\Models\General\SystemModules::$SM_EVENTS_INDEX))
                <li class="nav-item">
                    <a class="nav-link  " href="{{ route('admin.events.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Eventos</p>
                    </a>
                </li>
                @endif
                @if(securityAccess(App\Models\General\SystemModules::$SM_SUBSIDIARIES_INDEX))
                <li class="nav-item">
                    <a class="nav-link  " href="{{ route('admin.subsidiaries.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Filiais</p>
                    </a>
                </li>
                @endif
                <li class="nav-header ">
                    Financeiro
                </li>
                @if(securityAccess(App\Models\General\SystemModules::$SM_EXPENSES_INDEX))
                <li class="nav-item">
                    <a class="nav-link  " href="{{ route('admin.expenses.index')}}">
                        <i class="fas fa-fw fa-user "></i>
                        <p>Extratos</p>
                    </a>
                </li>
                @endif
            </ul>
        </nav>
    </div>

</aside>